#
# docker-compose.yml:
# * https://github.com/n8n-io/n8n-hosting/tree/main/docker-compose/withPostgres
# * https://github.com/n8n-io/self-hosted-ai-starter-kit/blob/main/docker-compose.yml
# конфиги: https://docs.n8n.io/hosting/configuration/environment-variables/
#

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_PORT=80
      - WEBHOOK_URL
      - N8N_EDITOR_BASE_URL
      - GENERIC_TIMEZONE=Europe/Moscow
      - N8N_HIDE_USAGE_PAGE=true
      - N8N_METRICS=true
      # Только для локальной разработки для обхода проблемы:
      # Your n8n server is configured to use a secure cookie,
      # however you are either visiting this via an insecure URL, or using Safari
      - N8N_SECURE_COOKIE=false
#      - N8N_LOG_LEVEL=debug
#      - N8N_LOG_LEVEL=info
#      - N8N_LOG_LEVEL=warn
#      - N8N_LOG_LEVEL=error
#      - N8N_LOG_LEVEL=silent
    hostname: n8n
    links:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/n8n:/home/node/.n8n
      # для сохранения файлов в локальный каталог (для отладки)
      - ./shared-files:/home/node/shared-files
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.deb24.localhost`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=80"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - backend

  init-ollama:
    image: ollama/ollama:latest
    container_name: ollama-pull-llama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; export OLLAMA_HOST=ollama:11434; ollama pull mxbai-embed-large; ollama pull llama3.1:8b"
    networks:
      - backend

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/qdrant:/qdrant/storage
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.deb24.localhost`)"

  # Local only
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    restart: unless-stopped
    ports:
      - '7474:7474' # HTTP-протокол
      - '7687:7687' # Bolt-протокол
    environment:
      - NEO4J_AUTH
#      - NEO4J_AUTH=none
    volumes:
      - ${DATA_PATH}/neo4j/data:/data

  # Local only
  # Требует установки community node: n8n-nodes-browserless
  # https://github.com/browserless/browserless
  browserless:
    image: ghcr.io/browserless/chromium
    hostname: browserless
    restart: unless-stopped
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=120000
      - TOKEN=${BROWSERLESS_TOKEN}
    networks:
      - backend

  # Авторизация: https://docs.stirlingpdf.com/Advanced%20Configuration/System%20and%20Security/
  # Языки для OCR https://docs.stirlingpdf.com/Advanced%20Configuration/OCR
  # Настройка https://hub.docker.com/r/stirlingtools/stirling-pdf
#  stirling-pdf:
#    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
#    hostname: stirling-pdf
#    volumes:
#      - ./tessdata:/usr/share/tessdata
#      - ./pipeline:/pipeline/
#    networks:
#      - frontend
#      - backend
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.stirling-pdf.rule=Host(`stirling-pdf.deb24.localhost`)"

  startup:
    build:
      context: .
      dockerfile: ./docker/startup/Dockerfile
    # смена владельца каталога, так как n8n запускается от непривилегированного пользователя
    command: chown startup:startup /home/node/.n8n
    volumes:
      - ${DATA_PATH}/n8n:/home/node/.n8n
    networks:
      - backend

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    hostname: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ${DATA_PATH}/postgresql:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - ${PG_PORT}:5432
    networks:
      - backend

  redis:
    image: redis:alpine
    hostname: redis
    restart: always
    volumes:
      - ${DATA_PATH}/redis:/data
    networks:
      - backend

volumes:
  ollama_storage:

networks:
  frontend:
    driver: bridge
    external: true
  backend:
    driver: bridge