#
# docker-compose.yml: https://github.com/n8n-io/n8n-hosting/tree/main/docker-compose/withPostgres
# конфиги: https://docs.n8n.io/hosting/configuration/environment-variables/
#

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_PORT=80
      - WEBHOOK_URL
      - N8N_EDITOR_BASE_URL
      - GENERIC_TIMEZONE=Europe/Moscow
      - N8N_HIDE_USAGE_PAGE=true
    hostname: n8n
    ports:
      - ${HTTP_PORT}:80
    links:
      - postgres
    volumes:
      - ${DATA_PATH}/n8n:/home/node/.n8n
      # для сохранения файлов в локальный каталог (для отладки)
      - ./files:/home/node/files
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_storage:/root/.ollama

  init-ollama:
    image: ollama/ollama:latest
    container_name: ollama-pull-llama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; export OLLAMA_HOST=ollama:11434; ollama pull mxbai-embed-large; ollama pull llama3.1:8b"

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    restart: unless-stopped
    ports:
      - ${QDRANT_PORT}:6333
    volumes:
      - ${DATA_PATH}/qdrant:/qdrant/storage

  startup:
    image: n8n_startup:${CI_COMMIT_SHA}
    # смена владельца каталога, так как n8n запускается от непривилегированного пользователя
    command: chown -R startup:startup /home/node/.n8n
    volumes:
      - ${DATA_PATH}/n8n:/home/node/.n8n

  postgres:
    image: n8n_postgres:${CI_COMMIT_SHA}
    hostname: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ${DATA_PATH}/postgresql:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - ${PG_PORT}:5432

volumes:
  ollama_storage: